; SFX indexes (see audio/sfx_pointers.asm)
	const_def

	const SFX_ITEM                        ; 00
	const SFX_KEY_ITEM                    ; 01
	const SFX_DEX_FANFARE_20_49           ; 02
	const SFX_DEX_FANFARE_50_79           ; 03
	const SFX_CAUGHT_MON                  ; 04
	const SFX_DEX_FANFARE_80_109          ; 05
	const SFX_FANFARE                     ; 06
	const SFX_GET_EGG_FROM_DAY_CARE_MAN   ; 07
	const SFX_LEVEL_UP                    ; 08
	const SFX_REGISTER_PHONE_NUMBER       ; 09
	const SFX_GET_TM                      ; 0a
	const SFX_GET_BADGE                   ; 0b
	const SFX_DEX_FANFARE_LESS_THAN_20    ; 0c
	const SFX_DEX_FANFARE_230_PLUS        ; 0d
	const SFX_2ND_PLACE                   ; 0e
	const SFX_FANFARE_2                   ; 0f
	const SFX_CHOOSE_A_CARD               ; 10
	const SFX_1ST_PLACE                   ; 11

;	const SFX_3RD_PLACE                   ; 
;	const SFX_GET_EGG_FROM_DAY_CARE_LADY  ; 
;	const SFX_MOVE_DELETED                ; 
;	const SFX_QUIT_SLOTS                  ; 
;	const SFX_DEX_FANFARE_140_169         ; 
;	const SFX_DEX_FANFARE_170_199         ; 
;	const SFX_DEX_FANFARE_200_229         ; 

	const SFX_POKEBALLS_PLACED_ON_TABLE   ; 12
	const SFX_POTION                      ; 13
	const SFX_FULL_HEAL                   ; 14
	const SFX_MENU                        ; 15
	const SFX_READ_TEXT                   ; 16
	const SFX_READ_TEXT_2                 ; 17
	const SFX_POISON                      ; 18
	const SFX_GOT_SAFARI_BALLS            ; 19
	const SFX_BOOT_PC                     ; 1a
	const SFX_SHUT_DOWN_PC                ; 1b
	const SFX_CHOOSE_PC_OPTION            ; 1c
	const SFX_ESCAPE_ROPE                 ; 1d
	const SFX_PUSH_BUTTON                 ; 1e
	const SFX_SECOND_PART_OF_ITEMFINDER   ; 1f
	const SFX_WARP_TO                     ; 20
	const SFX_WARP_FROM                   ; 21
	const SFX_CHANGE_DEX_MODE             ; 22
	const SFX_JUMP_OVER_LEDGE             ; 23
	const SFX_GRASS_RUSTLE                ; 24
	const SFX_FLY                         ; 25
	const SFX_WRONG                       ; 26
	const SFX_SQUEAK                      ; 27
	const SFX_STRENGTH                    ; 28
	const SFX_BOAT                        ; 29
	const SFX_WALL_OPEN                   ; 2a
	const SFX_PLACE_PUZZLE_PIECE_DOWN     ; 2b
	const SFX_ENTER_DOOR                  ; 2c
	const SFX_SWITCH_POKEMON              ; 2d
	const SFX_TALLY                       ; 2e
	const SFX_TRANSACTION                 ; 2f
	const SFX_EXIT_BUILDING               ; 30
	const SFX_BUMP                        ; 31
	const SFX_SAVE                        ; 32
	const SFX_POKEFLUTE                   ; 33
	const SFX_ELEVATOR_END                ; 34
	const SFX_THROW_BALL                  ; 35
	const SFX_BALL_POOF                   ; 36
	const SFX_FAINT                       ; 37
	const SFX_RUN                         ; 38
	const SFX_SLOT_MACHINE_START          ; 39
	const SFX_PECK                        ; 3a
	const SFX_KINESIS                     ; 3b
	const SFX_LICK                        ; 3c
	const SFX_POUND                       ; 3d
	const SFX_MOVE_PUZZLE_PIECE           ; 3e
	const SFX_COMET_PUNCH                 ; 3f
	const SFX_MEGA_PUNCH                  ; 40
	const SFX_SCRATCH                     ; 41
	const SFX_VICEGRIP                    ; 42
	const SFX_RAZOR_WIND                  ; 43
	const SFX_CUT                         ; 44
	const SFX_WING_ATTACK                 ; 45
	const SFX_WHIRLWIND                   ; 46
	const SFX_BIND                        ; 47
	const SFX_VINE_WHIP                   ; 48
	const SFX_DOUBLE_KICK                 ; 49
	const SFX_MEGA_KICK                   ; 4a
	const SFX_HEADBUTT                    ; 4b
	const SFX_HORN_ATTACK                 ; 4c
	const SFX_TACKLE                      ; 4d
	const SFX_POISON_STING                ; 4e
	const SFX_POWDER                      ; 4f
	const SFX_DOUBLESLAP                  ; 50
	const SFX_BITE                        ; 51
	const SFX_JUMP_KICK                   ; 52
	const SFX_STOMP                       ; 53
	const SFX_TAIL_WHIP                   ; 54
	const SFX_KARATE_CHOP                 ; 55
	const SFX_SUBMISSION                  ; 56
	const SFX_WATER_GUN                   ; 57
	const SFX_SWORDS_DANCE                ; 58
	const SFX_THUNDER                     ; 59
	const SFX_SUPERSONIC                  ; 5a
	const SFX_LEER                        ; 5b
	const SFX_EMBER                       ; 5c
	const SFX_BUBBLEBEAM                  ; 5d
	const SFX_HYDRO_PUMP                  ; 5e
	const SFX_SURF                        ; 5f
	const SFX_PSYBEAM                     ; 60
	const SFX_CHARGE                      ; 61
	const SFX_THUNDERSHOCK                ; 62
	const SFX_PSYCHIC                     ; 63
	const SFX_SCREECH                     ; 64
	const SFX_BONE_CLUB                   ; 65
	const SFX_SHARPEN                     ; 66
	const SFX_EGG_BOMB                    ; 67
	const SFX_SING                        ; 68
	const SFX_HYPER_BEAM                  ; 69
	const SFX_SHINE                       ; 6a
	const SFX_PSI_UNUSED                  ; 6b
	const SFX_RB_DEMO_LUNGE               ; 6c
	const SFX_NIDORAN_HIP                 ; 6d
	const SFX_SWITCH_POCKETS              ; 6e
SFX_NIDORAN_HOP EQU SFX_SWITCH_POCKETS
	const SFX_RB_VERSION_NAME_ENTRANCE    ; 6f
	const SFX_BURN                        ; 70
	const SFX_TITLE_SCREEN_ENTRANCE       ; 71
	const SFX_RBY_STOP_SLOTS              ; 72
	const SFX_GET_COIN_FROM_SLOTS         ; 73
	const SFX_PAY_DAY_GS                  ; 74
	const SFX_METRONOME                   ; 75
	const SFX_CALL                        ; 76
	const SFX_HANG_UP                     ; 77
	const SFX_NO_SIGNAL                   ; 78
	const SFX_SANDSTORM                   ; 79
	const SFX_ELEVATOR                    ; 7a
	const SFX_PROTECT                     ; 7b
	const SFX_SKETCH                      ; 7c
	const SFX_RAIN_DANCE                  ; 7d
	const SFX_AEROBLAST                   ; 7e
	const SFX_SPARK                       ; 7f
	const SFX_CURSE                       ; 80
	const SFX_RAGE                        ; 81
	const SFX_THIEF                       ; 82
	const SFX_THIEF_2                     ; 83
	const SFX_SPIDER_WEB                  ; 84
	const SFX_MIND_READER                 ; 85
	const SFX_NIGHTMARE                   ; 86
	const SFX_SNORE                       ; 87
	const SFX_SWEET_KISS                  ; 88
	const SFX_SWEET_KISS_2                ; 89
	const SFX_BELLY_DRUM                  ; 8a
	const SFX_TOXIC                       ; 8b
	const SFX_SLUDGE_BOMB                 ; 8c
	const SFX_FORESIGHT                   ; 8d
	const SFX_SPITE                       ; 8e
	const SFX_OUTRAGE                     ; 8f
	const SFX_PERISH_SONG                 ; 90
	const SFX_GIGA_DRAIN                  ; 91
	const SFX_ATTRACT                     ; 92
	const SFX_KINESIS_2                   ; 93
	const SFX_ZAP_CANNON                  ; 94
	const SFX_MEAN_LOOK                   ; 95
	const SFX_HEAL_BELL                   ; 96
	const SFX_RETURN                      ; 97
	const SFX_EXP_BAR                     ; 98
	const SFX_MILK_DRINK                  ; 99
	const SFX_PRESENT                     ; 9a
	const SFX_MORNING_SUN                 ; 9b
	const SFX_EGG_CRACK                   ; 9c
	const SFX_EVOLVED                     ; 9d
	const SFX_MASTER_BALL                 ; 9e
	const SFX_EGG_HATCH                   ; 9f
	const SFX_GS_INTRO_CHARIZARD_FIREBALL ; a0
	const SFX_GS_INTRO_POKEMON_APPEARS    ; a1
	const SFX_FLASH                       ; a2
	const SFX_GAME_FREAK_LOGO_GS          ; a3
	const SFX_NOT_VERY_EFFECTIVE          ; a4
	const SFX_DAMAGE                      ; a5
	const SFX_SUPER_EFFECTIVE             ; a6
	const SFX_BALL_BOUNCE                 ; a7
	const SFX_MOONLIGHT                   ; a8
	const SFX_ENCORE                      ; a9
	const SFX_BEAT_UP                     ; aa
	const SFX_BATON_PASS                  ; ab
	const SFX_BALL_WOBBLE                 ; ac
	const SFX_SWEET_SCENT                 ; ad
	const SFX_SWEET_SCENT_2               ; ae
	const SFX_HIT_END_OF_EXP_BAR          ; af
	const SFX_GIVE_TRADEMON               ; b0
	const SFX_GET_TRADEMON                ; b1
	const SFX_TRAIN_ARRIVED               ; b2
	const SFX_STOP_SLOT                   ; b3
	const SFX_2_BOOPS                     ; b4

; new to Crystal
	const SFX_GLASS_TING                  ; b5
	const SFX_GLASS_TING_2                ; b6
	const SFX_INTRO_UNOWN_1               ; b7
	const SFX_INTRO_UNOWN_2               ; b8
	const SFX_INTRO_UNOWN_3               ; b9
	const SFX_SHOCK_EMOTE                 ; ba
	const SFX_DITTO_TRANSFORM             ; bb
	const SFX_INTRO_SUICUNE_1             ; bc
	const SFX_EMOTE                       ; bd
	const SFX_INTRO_SUICUNE_2             ; be
	const SFX_INTRO_SUICUNE_3             ; bf
	const SFX_DITTO_BOUNCE                ; c0
	const SFX_INTRO_SUICUNE_4             ; c1
	const SFX_GAME_FREAK_PRESENTS         ; c2
	const SFX_TINGLE                      ; c3
	const SFX_INTRO_WHOOSH                ; c4
	const SFX_TWO_PC_BEEPS                ; c5
	const SFX_4_NOTE_DITTY                ; c6
	const SFX_TWINKLE                     ; c7
; imported
	const SFX_SHOOTING_STAR               ; c8
	const SFX_RBY_SING                    ; c9
	const SFX_HIP                         ; ca
	const SFX_HOP                         ; cb
	const SFX_RBY_WHOOSH                  ; cc
	const SFX_LOCK_ON                     ; cd
	const SFX_FLAIL                       ; ce
	const SFX_BALL_CLOSE                  ; cf
	const SFX_IN_LOVE                     ; d0
	const SFX_AMNESIA                     ; d1
	const SFX_EXP_BAR_FULL                ; d2
	const SFX_MIMIC_D3                    ; d3
	const SFX_MIMIC_D4                    ; d4
	const SFX_MIMIC_D5                    ; d5
	const SFX_MIMIC_D6                    ; d6
	const SFX_MIMIC_D7                    ; d7
	const SFX_MIMIC_D8                    ; d8
	const SFX_MIMIC_D9                    ; d9
	const SFX_BALL_SHAKE                  ; da
	const SFX_EGG_ROLL                    ; db
	const SFX_SMOKESCREEN                 ; dc
	const SFX_SPIKES_E1                   ; dd
	const SFX_SPIKES_E2                   ; de
	const SFX_RECOVER                     ; df
	const SFX_PAY_DAY                     ; e0
	const SFX_POKEFLUTE_HOME              ; e1
	const SFX_POKEFLUTE_NIGHT             ; e2
	const SFX_POKEFLUTE_DUNGEON           ; e3
; Chaos-exclusive
	const SFX_BLINK_E8                    ; e4
	const SFX_JUMP                        ; e5
	const SFX_DESCEND                     ; e6
	const SFX_GAME_FREAK_LOGO_CHAOS       ; e7
	const SFX_BLINK_EC                    ; e8
	const SFX_BURNOUT                     ; e9
	const SFX_FALL                        ; ea
	const SFX_STOP_IN_MIDAIR              ; eb
	const SFX_DASH                        ; ec
	const SFX_SONIC_BOOM                  ; ed
	const SFX_EMAIL_NOTIFICATION          ; ee
	const SFX_RECIEVE_ITEM                ; ef
	const SFX_CATCH_ITEM                  ; f0
	const SFX_REGISTER_EMAIL_BOOPS        ; f1
	const SFX_UNIVERSITY_TM               ; f2
	const SFX_ALMA_MATER_FANFARE          ; f3
	const SFX_PLANE_LANDING               ; f4
	const SFX_PLANE_TAKING_OFF            ; f5
	const SFX_GGG_FANFARE                 ; f6

	const SFX_UNUSED_E8
	const SFX_UNUSED_E9
	const SFX_YOSHI
	const SFX_BIG_YOSHI
NUM_SFX EQU const_value
