
BaseDesignations:
	db " Nidoran ",$81
	db " Nidoran ",$80
	db "  Slowpoke"
	db "Kangaskhan"
	db "   Rhyhorn"
	db "    Grimer"
	db "   Voltorb"
	db "    Gengar"
	db "   Marowak"
	db "  Nidoking"
	db " Nidoqueen"
	db " Exeggcute"
	db " Lickitung"
	db "Exeggcutor"
	db " Poliwrath"
	db "  Venusaur"
	db "   Spearow"
	db "    Rhydon"
	db "   Tangela"
	db " Blastoise"
	db "    Pinsir"
	db "  Arcanine"
	db "   Scyther"
	db "  Gyarados"
	db "  Shellder"
	db "    Cubone"
	db " Tentacool"
	db "    Lapras"
	db "    Gastly"
	db "    Crobat"
	db "   Starmie"
	db "   Slowbro"
	db "  Mr. Mime"
	db "   Psyduck"
	db "   Rattata"
	db "Aerodactyl"
	db "  Graveler"
	db "    Ponyta"

	db "   Murkrow"
	db "  Spinarak"
	db "    Togepi"
	db "   Siamais"
	db " Tyranitar"
	db "   Flaaffy"
	db "   Togetic"
	db "  Hoothoot"
	db "    Phanpy"
	db "  Slowking"
	db "  Houndour"
	db " Chikorita"
	db " Octillery"
	db "   Miltank"
	db "  Jumpluff"
	db " Hitmontop"
	db "    Ledyba"
	db "     Entei"
	db "   Sneasel"
	db "   Mantine"
	db "     Lugia"
	db "    Madame"
	db "  Delibird"
	db "  Remoraid"
	db "    Scizor"
	db "   Suicune"
	db "     Pichu"
	db "     Ho-oh"
	db "  Granbull"
	db "   Donphan"

	db "   Caditin"
	db "  Empeduck"
	db "  Flambear"
	db "    Sweote"
	db "  Metabeak"
	db "   Aqauria"
	db "    Trifox"
	db " Noctglide"
	db "  Dodaerie"
	db "Bellboyant"
	db "     Smujj"
	db "   Numpuff"
	db "   Wolfman"
	db "  Folicorn"
	db "   Lediury"
	db "   Snoburi"
	db " Porysphia"
	db "   Fosslix"
	db "  Pouchent"
	db "  Murphelt"
	db "  Assisdra"
	db "   Kicloud"
	db "Dugquintet"
	db "Coazigoast"
	db "    Appuck"
	db "  Toufense"
	db "    Antlog"
	db "   Glabbit"
	db "   Guarnid"
	db "Driscorina"
	db "     Orkid"
	db "    Croven"
	db "    Bomoca"
	db " Selenumia"
	db "  Reclinax"
	db " Sandscour"
	db "    Tearow"
	db "  Windkitt"
	db " Cosmoreas"
