	const_def
	const COMPOSER_NONE
	const COMPOSER_JUNICHI_MASUDA
	const COMPOSER_GO_ICHINOSE
	const COMPOSER_MORIKAZU_AOKI
	const COMPOSER_MINAKO_HAMANO
	const COMPOSER_SCOTT_CHENEY
	const COMPOSER_DANIEL_INGRAM
	const COMPOSER_WILLIAM_ANDERSON
	const COMPOSER_SOLO_ACAPELLO
	const COMPOSER_JACK_GETSCHMAN
	const COMPOSER_WOODEN_TOASTER
	const COMPOSER_JOSHUA_CRAPO
	const COMPOSER_ZUMI_DAXUYA
	const COMPOSER_JOSHUA_CRAPO_ANICOM
	const COMPOSER_UNCOMPOSED

ComposerList:
	db COMPOSER_NONE,             COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_WILLIAM_ANDERSON
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_WILLIAM_ANDERSON
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_WILLIAM_ANDERSON
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_SCOTT_CHENEY,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_JOSHUA_CRAPO
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JACK_GETSCHMAN,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JACK_GETSCHMAN,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_JUNICHI_MASUDA
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JACK_GETSCHMAN,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_SOLO_ACAPELLO,    COMPOSER_NONE
	db COMPOSER_MINAKO_HAMANO,    COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_JOSHUA_CRAPO
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_JOSHUA_CRAPO
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_DANIEL_INGRAM,    COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_JACK_GETSCHMAN
	db COMPOSER_DANIEL_INGRAM,    COMPOSER_NONE
	db COMPOSER_DANIEL_INGRAM,    COMPOSER_NONE

	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO,     COMPOSER_NONE
	db COMPOSER_SOLO_ACAPELLO,    COMPOSER_WOODEN_TOASTER
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_NONE
	db COMPOSER_WILLIAM_ANDERSON, COMPOSER_NONE
	db COMPOSER_MORIKAZU_AOKI,    COMPOSER_NONE
	db COMPOSER_MORIKAZU_AOKI,    COMPOSER_DANIEL_INGRAM
	db COMPOSER_MORIKAZU_AOKI,    COMPOSER_NONE
	db COMPOSER_MORIKAZU_AOKI,    COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE

	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE

	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE

	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_ZUMI_DAXUYA
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE

	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_GO_ICHINOSE,      COMPOSER_NONE
	db COMPOSER_GO_ICHINOSE,      COMPOSER_NONE

	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE
	db COMPOSER_JUNICHI_MASUDA,   COMPOSER_NONE

	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_UNCOMPOSED,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
	db COMPOSER_JOSHUA_CRAPO_ANICOM,COMPOSER_NONE
