PokemonNames::
    db      "BULBASAUR "
    db      "IVYSAUR   "
    db      "VENUSAUR  "
    db      "CHARMANDER"
    db      "CHARMELEON"
    db      "CHARIZARD "
    db      "SQUIRTLE  "
    db      "WARTORTLE "
    db      "BLASTOISE "
    db      "CATERPIE  "
    db      "METAPOD   "
    db      "BUTTERFREE"
    db      "WEEDLE    "
    db      "KAKUNA    "
    db      "BEEDRILL  "
    db      "PIDGEY    "
    db      "PIDGEOTTO "
    db      "PIDGEOT   "
    db      "RATTATA   "
    db      "RATICATE  "
    db      "SPEAROW   "
    db      "FEAROW    "
    db      "EKANS     "
    db      "ARBOK     "
    db      "PIKACHU   "
    db      "RAICHU    "
    db      "SANDSHREW "
    db      "SANDSLASH "
    db      "NIDORAN",$80,"  "
    db      "NIDORINA  "
    db      "NIDOQUEEN "
    db      "NIDORAN",$81,"  "
    db      "NIDORINO  "
    db      "NIDOKING  "
    db      "CLEFAIRY  "
    db      "CLEFABLE  "
    db      "VULPIX    "
    db      "NINETALES "
    db      "JIGGLYPUFF"
    db      "WIGGLYTUFF"
    db      "ZUBAT     "
    db      "GOLBAT    "
    db      "ODDISH    "
    db      "GLOOM     "
    db      "VILEPLUME "
    db      "PARAS     "
    db      "PARASECT  "
    db      "VENONAT   "
    db      "VENOMOTH  "
    db      "DIGLETT   "
    db      "DUGTRIO   "
    db      "MEOWTH    "
    db      "PERSIAN   "
    db      "PSYDUCK   "
    db      "GOLDUCK   "
    db      "MANKEY    "
    db      "PRIMEAPE  "
    db      "GROWLITHE "
    db      "ARCANINE  "
    db      "POLIWAG   "
    db      "POLIWHIRL "
    db      "POLIWRATH "
    db      "ABRA      "
    db      "KADABRA   "
    db      "ALAKAZAM  "
    db      "MACHOP    "
    db      "MACHOKE   "
    db      "MACHAMP   "
    db      "BELLSPROUT"
    db      "WEEPINBELL"
    db      "VICTREEBEL"
    db      "TENTACOOL "
    db      "TENTACRUEL"
    db      "GEODUDE   "
    db      "GRAVELER  "
    db      "GOLEM     "
    db      "PONYTA    "
    db      "RAPIDASH  "
    db      "SLOWPOKE  "
    db      "SLOWBRO   "
    db      "MAGNEMITE "
    db      "MAGNETON  "
    db      "FARFETCHD "
    db      "DODUO     "
    db      "DODRIO    "
    db      "SEEL      "
    db      "DEWGONG   "
    db      "GRIMER    "
    db      "MUK       "
    db      "SHELLDER  "
    db      "CLOYSTER  "
    db      "GASTLY    "
    db      "HAUNTER   "
    db      "GENGAR    "
    db      "ONIX      "
    db      "DROWZEE   "
    db      "HYPNO     "
    db      "KRABBY    "
    db      "KINGLER   "
    db      "VOLTORB   "
    db      "ELECTRODE "
    db      "EXEGGCUTE "
    db      "EXEGGUTOR "
    db      "CUBONE    "
    db      "MAROWAK   "
    db      "HITMONLEE "
    db      "HITMONCHAN"
    db      "LICKITUNG "
    db      "KOFFING   "
    db      "WEEZING   "
    db      "RHYHORN   "
    db      "RHYDON    "
    db      "CHANSEY   "
    db      "TANGELA   "
    db      "KANGASKHAN"
    db      "HORSEA    "
    db      "SEADRA    "
    db      "GOLDEEN   "
    db      "SEAKING   "
    db      "STARYU    "
    db      "STARMIE   "
    db      "MR. MIME  "
    db      "SCYTHER   "
    db      "JYNX      "
    db      "ELECTABUZZ"
    db      "MAGMAR    "
    db      "PINSIR    "
    db      "TAUROS    "
    db      "MAGIKARP  "
    db      "GYARADOS  "
    db      "LAPRAS    "
    db      "DITTO     "
    db      "EEVEE     "
    db      "VAPOREON  "
    db      "JOLTEON   "
    db      "FLAREON   "
    db      "PORYGON   "
    db      "OMANYTE   "
    db      "OMASTAR   "
    db      "KABUTO    "
    db      "KABUTOPS  "
    db      "AERODACTYL"
    db      "SNORLAX   "
    db      "ARTICUNO  "
    db      "ZAPDOS    "
    db      "MOLTRES   "
    db      "DRATINI   "
    db      "DRAGONAIR "
    db      "DRAGONITE "
    db      "MEWTWO    "
    db      "MEW       "
    db      "CHIKORITA "
    db      "BAYLEEF   "
    db      "MEGANIUM  "
    db      "CYNDAQUIL "
    db      "QUILAVA   "
    db      "TYPHLOSION"
    db      "TOTODILE  "
    db      "CROCONAW  "
    db      "FERALIGATR"
    db      "SENTRET   "
    db      "FURRET    "
    db      "HOOTHOOT  "
    db      "NOCTOWL   "
    db      "LEDYBA    "
    db      "LEDIAN    "
    db      "SPINARAK  "
    db      "ARIADOS   "
    db      "CROBAT    "
    db      "CHINCHOU  "
    db      "LANTURN   "
    db      "PICHU     "
    db      "CLEFFA    "
    db      "IGGLYBUFF "
    db      "TOGEPI    "
    db      "TOGETIC   "
    db      "NATU      "
    db      "XATU      "
    db      "MAREEP    "
    db      "FLAAFFY   "
    db      "AMPHAROS  "
    db      "BELLOSSOM "
    db      "MARILL    "
    db      "AZUMARILL "
    db      "SUDOWOODO "
    db      "POLITOED  "
    db      "HOPPIP    "
    db      "SKIPLOOM  "
    db      "JUMPLUFF  "
    db      "AIPOM     "
    db      "SUNKERN   "
    db      "SUNFLORA  "
    db      "YANMA     "
    db      "WOOPER    "
    db      "QUAGSIRE  "
    db      "ESPEON    "
    db      "UMBREON   "
    db      "MURKROW   "
    db      "SLOWKING  "
    db      "MISDREAVUS"
    db      "UNOWN     "
    db      "WOBBUFFET "
    db      "GIRAFARIG "
    db      "PINECO    "
    db      "FORRETRESS"
    db      "DUNSPARCE "
    db      "GLIGAR    "
    db      "STEELIX   "
    db      "SNUBBULL  "
    db      "GRANBULL  "
    db      "QWILFISH  "
    db      "SCIZOR    "
    db      "SHUCKLE   "
    db      "HERACROSS "
    db      "SNEASEL   "
    db      "TEDDIURSA "
    db      "URSARING  "
    db      "SLUGMA    "
    db      "MAGCARGO  "
    db      "SWINUB    "
    db      "PILOSWINE "
    db      "CORSOLA   "
    db      "REMORAID  "
    db      "OCTILLERY "
    db      "DELIBIRD  "
    db      "MANTINE   "
    db      "SKARMORY  "
    db      "HOUNDOUR  "
    db      "HOUNDOOM  "
    db      "KINGDRA   "
    db      "PHANPY    "
    db      "DONPHAN   "
    db      "PORYGON2  "
    db      "STANTLER  "
    db      "SMEARGLE  "
    db      "TYROGUE   "
    db      "HITMONTOP "
    db      "SMOOCHUM  "
    db      "ELEKID    "
    db      "MAGBY     "
    db      "MILTANK   "
    db      "BLISSEY   "
    db      "RAIKOU    "
    db      "ENTEI     "
    db      "SUICUNE   "
    db      "LARVITAR  "
    db      "PUPITAR   "
    db      "TYRANITAR "
    db      "LUGIA     "
    db      "HO-OH     "
    db      "CELEBI    "
;    db      "-FILLER-  "
;    db      "-FILLER-  "
;    db      "-FILLER-  "
;    db      "-FILLER-  "
;    db      "-FILLER-  "
    db      "ORKID     "
    db      "SYNTIQUE  "
    db      "PHOTORDEN "
    db      "FLAMBEAR  " ; SW97
    db      "VOLBEAR   " ; SW97
    db      "DYNABEAR  " ; SW97
    db      "CRUZ      " ; SW97
    db      "AQUACENT  " ; SW97
    db      "AQUARIA   " ; SW97
    db      "CROVEN    "
    db      "ASTROVEN  "
    db      "NOCTGLIDE "
    db      "SNOBURI   " ; Draft
    db      "SNOBUSTER " ; Draft
    db      "ARBUGS    " ; Draft
    db      "WILLOFUDD " ; Draft
    db      "TRIFOX    " ; SW97
    db      "BURGELA   " ; SW97
    db      "TENTACRIME"
    db      "NUMPUFF   " ; SW97
    db      "MIGHTALEX "
    db      "QUAGAMI   "
    db      "QUAILTER  " ; Draft
    db      "STAFFBIRD " ; Draft
    db      "ORSCHUL   " ; SW97
    db      "MOUNDIVER " ; Draft
    db      "MOLAMBINO " ; SW97
    db      "ANGORE    " ; SW97
    db      "GROTESS   " ; SW97
    db      "SAILWING  " ; Draft
    db      "PARABUD   " ; SW97
    db      "TIERACNID "
    db      "METABEAK  "
    db      "CRANEST   "
    db      "LYKWYSE   " ; SW97
    db      "DODAERIE  " ; SW97
    db      "SUNTHESIA "
    db      "TOUFENSE  " ; Draft
    db      "SIAMAIS   " ; SW97
    db      "RAKUKI    " ; Draft
    db      "COINTEN   " ; SW97
    db      "GATOLL    " ; SW97
    db      "BELLBOYANT" ; SW97
    db      "STARELLO  "
    db      "LIODEW    "
    db      "UNILIGHT  "
    db      "ALIDUSK   "
    db      "LEDIURY   "
    db      "FOLICORN  " ; SW97
    db      "WHISPEON  "
    db      "ASSEMBLEON"
    db      "TURBANN   " ; SW97
    db      "SMUJJ     " ; SW97
    db      "DRAGONISCE"
    db      "KICLOUD   "
    db      "RUFFY     " ; SW97
    db      "APPUCK    "
    db      "ALREM     "
    db      "MURPHELT  "
    db      "TIARANT   "
    db      "SILVEALTH "
    db      "SEARCHLE  "
    db      "BELMITT   " ; SW97
    db      "MILCALF   "
    db      "BOMOCA    " ; SW97
    db      "DELFLAP   "
    db      "KOTORA    " ; SW97
    db      "RAITORA   " ; SW97
    db      "MADAME    " ; SW97
    db      "KURSTRAW  " ; SW97
    db      "PANGSHI   " ; SW97
    db      "SCAFAROW  " ; Draft
    db      "RECLINAX  "
    db      "MOSCARF   " ; Draft
    db      "FLIDER    " ; Draft
    db      "PLUX      " ; SW97
    db      "HOUNDREAD "
    db      "WOLFMAN   " ; SW97
    db      "WARWOLF   " ; SW97
    db      "PORYSPHIA " ; SW97
    db      "RAVERMIN  "
    db      "FOSSLIX   "
    db      "MAGNEVEN  "
    db      "DONKRANK  "
    db      "CHOAKING  "
    db      "SANDSCOUR "
    db      "TEAROW    "
    db      "NOHTYP    "
    db      "VENOCLOTH "
    db      "DUGQUINTET"
    db      "EMPEDUCK  "
    db      "ALPHAPE   "
    db      "PINCHLER  "
    db      "POUCHENT  "
    db      "OMANOVA   "
    db      "KABOULDER "
    db      "COATRET   "
    db      "SHUVEL    "
    db      "COAZIGOAST" ; Draft
    db      "WINDKITT  " ; Draft
    db      "TODBRUSH  " ; Draft
    db      "SEWMA     "
    db      "ANIMADISE "
    db      "MARLOON   "
    db      "ASSISDRA  "
    db      "SCOOTEN   "
    db      "SWEOTE    "
    db      "GRIFLET   "
    db      "CIRRIFFON "
    db      "COSMOREAS "
    db      "LAROON    "
    db      "CADITIN   "
    db      "CHRYSALTY "
    db      "DRYTHON   " ; Draft
    db      "ANTLOG    " ; Draft
    db      "KOALIMB   " ; Draft
    db      "HIGHPO    " ; Draft
    db      "GLABBIT   " ; Draft
    db      "CYCORPION " ; Draft
    db      "GUARNID   " ; Draft
    db      "SQUIDRILL " ; Draft
    db      "PARROBRASS" ; Draft
    db      "FLINJA    " ; Draft
    db      "SHELLAPTOR" ; Draft
    db      "GOBELDORL "
    db      "CENTIR    "
    db      "DRISCORINA"
    db      "ARLURRY   "
    db      "MAGENZA   "
    db      "ILLUSIRO  "
    db      "HELICELIA "
    db      "SELENUMIA "
    db      "PARBELL   "