SongNames:
    db  "NOTHING             "
    db  "RSC:Title Screen    "
    db  "RS:Opening 1        "
    db  "RS:Opening 2        "
    db  "RSC:Main Menu       "
    db  "RSC:Heal -PMC-      "
    db  "RSC:Heal -ELSE-     "
    db  "RSC:Route 49-51     "
    db  "RSC:Route 55-60     "
    db  "RSC:Solar Conference"
    db  "RSC:Route 61-66     "
    db  "RSC:Route 52-54     "
    db  "RSC:Time Capsule    "
    db  "RSC:Mom             "
    db  "RSC:Guidepost       "
    db  "RSC:House Enroute   "
    db  "RSC:Pokemon Center  "
    db  "RSC:Abandoned PMC   "
    db  "RSC:Cottage Town    "
    db  "RSC:Traversal City  "
    db  "RSC:Wild Mon Fight  "
    db  "RSC:Trainer Fight   "
    db  "RSC:Gym Leader Fight"
    db  "RSC:Party Host Fight"
    db  "RSC:Champion Fight  "
    db  "RSC:Parker Fight    "
    db  "RSC:! Warden        "
    db  "RSC:! Girl          "
    db  "RSC:! Maniac        "
    db  "RSC:! Youth         "
    db  "RSC:! Woman         "
    db  "RSC:! Siblings      "
    db  "RSC:! Party Host    "
    db  "RSC:! Artist        "
    db  "RSC:! Team Havoc    "
    db  "RSC:Shaggy Appears  "
    db  "RSC:Shaggy Leaves   "
    db  "RSC:Professor Larch "
    db  "RSC:Capture Win     "
    db  "RSC:Wild Pokemon Win"
    db  "RSC:Trainer Win     "
    db  "RSC:Gym Leader Win  "
    db  "RSC:Gym             "
    db  "RSC:Trixie's Perf.  "
    db  "RSC:Cycling         "
    db  "RSC:Hall of Fame    "
    db  "RSC:Oddish Farm     "
    db  "RSC:Golem Palace    "
    db  "RSC:Walking W/ Apes "
    db  "RSC:Major Event     "
    db  "RSC:Staff Roll      "
    db  "RSC:THE END         "
    db  "RSC:Journey         "
    db  "RSC:S.S. Vapor      "
    db  "RSC:Lighthouse      "
    db  "RSC:Crusading!      "
    db  "RSC:Hypercoin City  "
    db  "RSC:Mt. Vacuum      "
    db  "RSC:Havoc Overture  "
    db  "RSC:Norgeo Town     "
    db  "RSC:Portite City    "
    db  "RSC:Printer         "
    db  "RSC:Departure Scene "
    db  "RSC:Surfing         "
    db  "RSC:Stamp Town      "
    db  "RSC:Havoc Hideout   "
    db  "RSC:Trade Menu      "
    db  "RSC:Trade Menu      "
    db  "RSC:Watchin' Over Me"
    db  "RSC:PokeFlute Medley"
    db  "RSC:BFF Lullaby     "
    db  "RSC:Morning March   "
    db  "Ch:Zach Appears     "
    db  "Ch:Marloon Appears  "
    db  "Ch:Equine Trio Fight"
    db  "Ch:Sonic Rainboom OP"
    db  "Ch:Wonderbolt Acad. "
    db  "Ch:Mobile Connection"
    db  "Ch:Battle Tower     "
    db  "Ch:Profile Menu     "
    db  "Ch:B.T. Lobby       "
    db  "Ch:PokeCom. Center  "
    db  "HR:Pallet Town      "
    db  "HR:Pokemon Center   "
    db  "HR:Gym              "
    db  "HR:Viridian City    "
    db  "HR:Cerulean City    "
    db  "HR:Celadon City     "
    db  "HR:Cinnabar Island  "
    db  "HR:Vermillion City  "
    db  "HR:Lavender Town    "
    db  "HR:SS Anne          "
    db  "HR:Prof. Oak's Here "
    db  "HR:Rival's Here     "
    db  "HR:Rival Leaves     "
    db  "HR:Guidepost        "
    db  "HR:Major Event      "
    db  "HR:Heal -Mon Center-"
    db  "HR:Route 1-2        "
    db  "HR:Route 24-25      "
    db  "HR:Route 3-10, 16-22"
    db  "HR:Route 11-15      "
    db  "HR:Route 23         "
    db  "HR:Gym Leader Fight "
    db  "HR:Trainer Fight    "
    db  "HR:Wild Mon Fight   "
    db  "HR:Champ Blue Fight "
    db  "HR:Trainer Win      "
    db  "HR:Wild Pokemon Win "
    db  "HR:Gym Leader Win   "
    db  "HR:Title Screen     "
    db  "HR:Staff Roll       "
    db  "HR:Hall of Fame     "
    db  "HR:Professor Oak    "
    db  "HR:Jigglypuff Solo  "
    db  "HR:Cycling          "
    db  "HR:Surfing          "
    db  "HR:Game Corner      "
    db  "HR:Opening Movie    "
    db  "HR:Rocket Hideout   "
    db  "HR:Viridian Forest  "
    db  "HR:Mt. Moon         "
    db  "HR:Cinnabar Mansion "
    db  "HR:Pokemon Tower    "
    db  "HR:Silph Co. Hostage"
    db  "HR:! Bad Trainer    "
    db  "HR:! Female Trainer "
    db  "HR:! Male Trainer   "
    db  "HR:Sevii Route      "
    db  "HR:Sevii Island 4/5 "
    db  "HR:Sevii Island 6/7 "
    db  "HR:Pallet Town -HOF-"
    db  "HR:Rival's Here -22-"
    db  "HR:Rival Leaves -22-"
    db  "HR:SS Anne          "
    db  "HR:Capture Win      "
    db  "Headetown           "
    db  "Aquatown            "
    db  "Angel City          "
    db  "Celltown            "
    db  "Routes 1-4, 7-11, 13"
    db  "Union Station       "
    db  "Gaming/Theater Cplx."
    db  "! Student           "
    db  "Ending(All it Takes)"
