Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3, Cries
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell

	dba Cry_Crow
	dba Cry_Derble4
	dba Cry_Derble1
	dba Cry_Feline
	dba Cry_Tyranitar
	dba Cry_Bleet1
	dba Cry_Derble2
	dba Cry_Hoothoot
	dba Cry_Phanpy
	dba Cry_Slowking
	dba Cry_Growl
	dba Cry_Chikorita
	dba Cry_Roar60
	dba Cry_Miltank
	dba Cry_Cottoncat
	dba Cry_Hitmontop
	dba Cry_Ledyba
	dba Cry_Tiger
	dba Cry_Sneasel
	dba Cry_Mantine
	dba Cry_Lugia
	dba Cry_Madame
	dba Cry_Roar30
	dba Cry_Roar40
	dba Cry_Roar50
	dba Cry_Suicune
	dba Cry_Mouse
	dba Cry_HoOh
	dba Cry_Granbull
	dba Cry_Donphan

	dba Cry_Earthtron
	dba Cry_SpearowOld
	dba ProtoCry_Crow
	dba ProtoCry_Derble4
	dba ProtoCry_Hoothoot
	dba ProtoCry_Tiger
	dba ProtoCry_Sneasel
	dba Cry_Lediury
	dba Cry_Yoshi
	dba Cry_BigYoshi
	dba Cry_Fosslix
	dba Cry_Pouchent
	dba Cry_Murphelt
	dba Cry_Assisdra
	dba Cry_Kicloud
	dba Cry_Dugquintet
	dba Cry_Coazigoast
	dba Cry_Appuck
	dba Cry_Toufense
	dba Cry_Antlog
	dba Cry_Glabbit
	dba Cry_Guarnid
	dba Cry_Driscorina
	dba Cry_Orkid
	dba Cry_Croven
	dba Cry_Cranest
	dba Cry_Selenumia
	dba Cry_Reclinax
	dba Cry_Sandscour
	dba Cry_Tearow
	dba Cry_Windkitt
	dba Cry_Cosmoreas
	assert_table_length NUM_CRIES
